services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: my_app_dev
      POSTGRES_USER: my_app_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U my_app_user -d my_app_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
